# Generated by Django 4.0.2 on 2022-03-18 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('todomodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='todo.todomodel')),
                ('title', models.CharField(max_length=100)),
                ('repo_link', models.URLField(blank=True, null=True)),
            ],
            bases=('todo.todomodel',),
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('todomodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='todo.todomodel')),
                ('todo_text', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('todo_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.project')),
            ],
            bases=('todo.todomodel',),
        ),
    ]
